
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: [Minimal Winds]
description: [Some thoughts while the winds don't take them away]
